# Defines the Docker services and how they interact.
version: '3.8'

services:
  etl_pipeline:
    build: .
    container_name: etl_pipeline
    command: python etl_pipeline.py
    volumes:
      - .:/app

  address_api:
    build: .
    container_name: address_api
    command: python address_api.py
    ports:
      - "5001:5000"
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"