FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask==2.3.3 elasticsearch==7.17.9

COPY es_search_api.py .

EXPOSE 5003

CMD ["python", "es_search_api.py"]
